services:
  - type: web
    name: qr-code-server
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: qr-code-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true  # Render will auto-generate a secure secret
      - key: CLOUDINARY_CLOUD_NAME
        sync: false  # You'll manually set this in Render's dashboard
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://p12pr.vercel.app
      - key: ALLOWED_ORIGINS
        value: https://p12pr.vercel.app,http://localhost:3000

databases:
  - name: qr-code-db
    databaseName: qr-code
    user: qr-code-user